In [ ]:
import keras
keras.__version__

'2.9.0'

In [ ]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
train_images.shape

(60000, 28, 28)

In [ ]:
len(train_labels)

60000

In [ ]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
len(test_labels)

10000

In [ ]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [ ]:
from keras import models
from keras import layers
from keras.layers import Dropout

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(Dropout(0.4))
network.add(layers.Dense(256, activation='tanh', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [ ]:
network.compile(optimizer='adam',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [ ]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [ ]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [ ]:
network.fit(train_images, train_labels, epochs=10, batch_size=128)

Epoch 1/10
469/469 [==============================] - 6s 12ms/step - loss: 0.2631 - accuracy: 0.9204
Epoch 2/10
469/469 [==============================] - 6s 13ms/step - loss: 0.1199 - accuracy: 0.9640
Epoch 3/10
469/469 [==============================] - 6s 13ms/step - loss: 0.0917 - accuracy: 0.9708
Epoch 4/10
469/469 [==============================] - 5s 12ms/step - loss: 0.0753 - accuracy: 0.9759
Epoch 5/10
469/469 [==============================] - 5s 12ms/step - loss: 0.0624 - accuracy: 0.9796
Epoch 6/10
469/469 [==============================] - 6s 12ms/step - loss: 0.0550 - accuracy: 0.9818
Epoch 7/10
469/469 [==============================] - 6s 12ms/step - loss: 0.0494 - accuracy: 0.9836
Epoch 8/10
469/469 [==============================] - 6s 12ms/step - loss: 0.0437 - accuracy: 0.9859
Epoch 9/10
469/469 [==============================] - 6s 12ms/step - loss: 0.0422 - accuracy: 0.9857
Epoch 10/10
469/469 [==============================] - 6s 13ms/step - loss: 0.0393 - accura

In [ ]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

313/313 [==============================] - 2s 4ms/step - loss: 0.0586 - accuracy: 0.9833


In [ ]:
print('test_acc:', test_acc)

test_acc: 0.983299970626831
